### ISSUE TITLE
Error using this Library in RN 0.69.5

### ISSUE THREAD

**Issue by Nibycz** [smartameer/rn-snackbar-component#10]
Hello, 
i got following Error when im trying to use the Snackbar in RN 0.69.5

<img width="323" alt="grafik" src="https://user-images.githubusercontent.com/46518188/188615758-7559d16a-f803-463f-94c7-4ef642f379c5.png">

Is there any Workaround for it ? or can the mantainer maybe fix this?

Thanks alot.

**Comment by tt-mp** [comment]
Same issue. Thank you!

**Comment by Nibycz** [comment]
There is a PR. Maybe @smartameer can approve this?

**Comment by smartameer** [comment]
Merged PR #11 
Released v0.0.7
